name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for highlighting this issue. We genuinely appreciate your effort!"
        pr-message: "🎉 Welcome to Data.HashFunction! Your first pull request is a significant milestone, and we're thrilled to have your contribution. Let's create something amazing together!"
